### ISSUE TITLE
RST check

### ISSUE THREAD

**Issue by petrus-v** [moylop260/pylint-oca#1]
Hi!

Thanks for making this project and spending time on it.

This is a question more than an issue, reading around code source.
Have you consider [restructuredtext_lint](https://pypi.python.org/pypi/restructuredtext_lint) instead expected [rst2html.py](https://github.com/moylop260/pylint-oca/blob/master/pylint_oca/misc.py#L120-L129) in the path ?

**Comment by moylop260** [comment]
@petrus-v 
Good point!
Thank you I will check it

**Comment by petrus-v** [comment]
Thank you! 

I'll try to use it as pre-commit hook, I let you know if I got some issues.

regards,

**Comment by moylop260** [comment]
@petrus-v 
I'll appreciate very much
Thank you!
