### ISSUE TITLE
[W8102(copy-wo-api-one), Model.copy] Missing api.one in copy function. Pylint rule must be deprecated

### ISSUE THREAD

**Issue by yaniaular** [moylop260/pylint-oca#20]
I have a pylint error:

```
[W8102(copy-wo-api-one), Model.copy] Missing api.one in copy function.
```

But, the api.one is deprecated by this issue https://github.com/odoo/odoo/pull/8527 

I try with api.model and api.multi on the copy method and the error persists.

Thanks for the help

**Comment by yaniaular** [comment]
@moylop260 Do you assign you this issue?

**Comment by moylop260** [comment]
Fixed
