### ISSUE TITLE
except Exception, e

### ISSUE THREAD

**Issue by lepistone** [moylop260/pylint-oca#3]
the line

https://github.com/moylop260/pylint-oca/blob/master/pylint_oca/misc.py#L154

uses a deprecated syntax that is ambiguous with `except (ExceptionOne, ExceptionTwo)`. `as` would be better than the comma.

Thanks!

**Comment by moylop260** [comment]
@lepistone 
Ok I got it
Thank you
I will consider to change it

**Comment by moylop260** [comment]
Fixed here: https://github.com/moylop260/pylint-oca/pull/7
Thank you!

**Comment by moylop260** [comment]
@dreispt
Your feedback is welcome too, before of create oca/project.
